### ISSUE TITLE
When rename filename, an error ...

### ISSUE THREAD

**Issue by Ryoga1016** [RainCat1998/obsidian-custom-attachment-location#71] opened 2024-08-08 00:11 UTC
![afe029bd3647a5f57391f0070b867f5](https://github.com/user-attachments/assets/5d9caddb-225b-483a-90cb-e73ec30e4231)
like this, and use "Collect attachments in current note" may be occurred.

**Comment by catacgc** [comment] 2024-08-08 08:06
Happens if you use the rename folder feature. 
<img width="815" alt="image" src="https://github.com/user-attachments/assets/8d2f37d9-456c-4b30-ba5a-b1074ee19a15">

**Comment by mnaoumov** [comment] 2024-08-12 07:02
@Ryoga1016 @catacgc Cannot reproduce the issue. Please provide a sample vault and a video with the issue

**Comment by catacgc** [comment] 2024-08-12 10:32
It's actually fairly easy to reproduce (empty, new vault):

- These settings:
<img width="633" alt="image" src="https://github.com/user-attachments/assets/2f04a2ac-ad90-41d9-b681-7fad26f41090">

- Create new file (Untitled)
- Paste an image
- Rename the file

**Comment by mnaoumov** [comment] 2024-08-13 08:35
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.6.0

**Closed by mnaoumov** 2024-08-13 08:35 UTC
Labels: bug
