### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'getPathForFile')

### ISSUE THREAD

**Issue by ruinmi** [RainCat1998/obsidian-custom-attachment-location#120] opened 2024-11-14 05:17 UTC
### Description

![image](https://github.com/user-attachments/assets/0fcac5df-d255-41c2-8088-058000a8470b)

### Steps to Reproduce

1. Open the app, and this pops up.

### Expected Behavior

-

### Actual Behavior

-

### Environment Information

- **Plugin Version**:  4.28.0
- **Obsidian Version**: v1.7.6
- **Operating System**: Windows 10

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by ruinmi** [comment] 2024-11-14 05:18
here is settings.

file-${date:YYYYMMDDHHmmssSSS}
![image](https://github.com/user-attachments/assets/6cc18647-4f38-4a78-8617-9b02390aad3d)

**Comment by mnaoumov** [comment] 2024-11-14 16:04
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.28.1

However, the problem caused by the fact you are using older Obsidian Installer that had older Electron version.

If you execute command `Show debug info` you would see `Installer version: v1.6.3` (or earlier)

**Closed by mnaoumov** 2024-11-14 16:04 UTC
Labels: bug
