### ISSUE TITLE
[BUG] Image pasted from clipboard as .octet-stream and in wrong location

### ISSUE THREAD

**Issue by daeh** [RainCat1998/obsidian-custom-attachment-location#100] opened 2024-09-22 21:48 UTC
I've been using this plugin for years, so thanks for all the work in developing it.

I'm having a new issue, I think it just started within the last couple days (well after the release of 4.22.1), so I'm not sure what the root cause is, possibly an interaction with the Obsidian version.

Now, when I paste an image from the clipboard, it's inserted into the note as a `.octet-stream` file in the Obsidian-specified attachment location, rather than as a png in the location specified by this plugin. 

E.g. a pasted link is:
`![[../Attachments/Pasted image 20240922172957.octet-stream]]`

If I drag an image into the note, everything works as intended. E.g. a dragged and dropped image is:

`![[_resources/test note.assets/image.png]]`

If I turn off this plugin, and paste an image from the clipboard, it's pasted as a png in Obsidian's default folder (as expected). E.g.
`![[../Attachments/Pasted image 20240922173247.png]]`

And if I paste an image from the clipboard into Typora, it's inserted as a png.

---

So it looks like it's something to do with this plugin to me, but I'm not sure how to debug from here. It looks like the plugin is trying to take over the default Obsidian pasted image process but isn't succeeding, so it ends up in the Obsidian-specified file location but as a different file format.

https://github.com/user-attachments/assets/26c56435-2344-460c-9ab4-014d757dbbe7

---

I didn't see anything that looked useful in the developer console, but these are the messages:

```
plugin:obsidian-custom-attachment-location:1770 chainAsyncFn:end Objectduration: 56timestampEnd: 1727040557009timestampStart: 1727040556953[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
plugin:obsidian-custom-attachment-location:8522 Handle Note Paste
```

---

Obsidian: Version 1.7.2 (Installer 1.6.7)
Custom Attachment Location: 4.22.1
MacOS 14.7 (M2 Max)

Settings:
location for new attachments: `./_resources/${filename}.assets`
pasted file name: `file-${date:YYYYMMDDHHmmssSSS}`

![CleanShot 2024-09-22 at 17 54 44](https://github.com/user-attachments/assets/9e0c45cc-aa90-4db8-b95a-c2b62bdee4b5)

**Comment by mnaoumov** [comment] 2024-09-22 22:13
@daeh you didn't follow the bug template. You had to attach the vault with the problem

**Comment by mnaoumov** [comment] 2024-09-23 00:06
Could not reproduce

https://github.com/user-attachments/assets/d62f41eb-e88e-4faf-a443-4b9a523d7c87

**Comment by daeh** [comment] 2024-09-23 16:41
Thanks for the quick response. I'm going to be preoccupied for a bit and not sure when I'll have time to dig into what's going on with my setup. I'll close this for now and reopen if I make a minimal vault that reproduces the issue.

**Comment by Thundercraft5** [comment] 2024-11-19 17:23
I can confirm this bug is present in my vault, even with all my other plugins **off**. I am currently investigating what the actual cause may be (settings file, workspace etc.).

**Comment by mnaoumov** [comment] 2024-11-19 17:38
@Thundercraft5 if you take a copy of your vault and remove all notes from it, is it still happening?

**Comment by Thundercraft5** [comment] 2024-11-19 22:14
Just tested; I copied the `.obsidian` folder to a new folder and tested. 

In all my tests the attachments went to the `/Attachments`. After some hunting around I found that the [Paste Mode](https://github.com/jglev/obsidian-paste-mode?tab=readme-ov-file#dynamic-attachment-saving) and [Paste Image Rename] plugin seems to be the culprit. These conflict with the plugin unsurprisingly, in my test vault disabling these fixed the issue.

**Comment by mnaoumov** [comment] 2024-11-20 00:16
@Thundercraft5 can you still attach the copy of the vault and the video so I can see if I can make my plugin compatible with others?

**Comment by Thundercraft5** [comment] 2024-11-21 15:49
Here's a minimal reproduction vault + the video as requested:

https://github.com/user-attachments/assets/a74d016b-5068-48f1-a0d5-ac068c48959a
[obsidian.zip](https://github.com/user-attachments/files/17848471/obsidian.zip)

**Comment by mnaoumov** [comment] 2024-11-26 01:11
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.29.0

**Closed by mnaoumov** 2024-11-26 01:11 UTC
Labels: bug, question
