### ISSUE TITLE
numbers are not pasted in  properties type : number after update.

### ISSUE THREAD

**Issue by hwp300** [RainCat1998/obsidian-custom-attachment-location#73] opened 2024-08-08 13:04 UTC
I updated the plug-in after using it without updating. Since then, there has been a error where I can't paste a number into properties type: number. I can paste number into properties type: list or properties type: text.

I can't remember the version I installed before the update, so I randomly installed the 0.0.8 version and a error  disappeared.

My first time using Obsidian was on January 17, 2024, so the first version I installed won't be the 0.0.8 version, but all of the relases have changed recently, so I installed the 0.0.8 version, and I don't know when the error started.

Of course, other plugins like this one have been updated for the first time in a while, so maybe it's a different plugin problem or an error that occurred in conflict with another plug-in. However, when I rolled back only this plug-in to version 0.0.8, the error disappeared and I'm writing here.

**Comment by mnaoumov** [comment] 2024-08-12 06:57
@hwp300 Cannot reproduce the issue. Please provide a sample vault and a video with the issue

**Comment by hwp300** [comment] 2024-08-12 12:29
I sent a video that I only installed this plugin and reproduce the issue to mnaoumov@gmail.com.
Thank you.

**Comment by mnaoumov** [comment] 2024-08-13 08:27
@hwp300 I don't see an email with the video. Please resend it, or upload here

**Comment by hwp300** [comment] 2024-08-15 07:05
error is disappeared at 0.0.8 and 0.0.9 version.


https://github.com/user-attachments/assets/e2c7ff45-a95f-4a7b-88de-5e1f584507de

**Comment by mnaoumov** [comment] 2024-08-15 07:32
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.7.0

**Closed by mnaoumov** 2024-08-15 07:32 UTC
Labels: bug, question

**Comment by hwp300** [comment] 2024-08-16 08:18
Thank you!
