### ISSUE TITLE
When I rename a .md file, don't update backlinks - error with this plugin is displayed

### ISSUE THREAD

**Issue by Kayfum** [RainCat1998/obsidian-custom-attachment-location#96] opened 2024-09-13 14:01 UTC
When I rename a .md file, it don't update backlinks and an error with plugin custom-attachment-location is displayed. If I disable the plugin, it works.
This plugin is super useful for me, so I don't want to remove it.
Do you know how to solve it please?
Many thanks in advance!

**Comment by mnaoumov** [comment] 2024-09-13 14:03
Which error are you getting?

**Comment by Kayfum** [comment] 2024-09-13 14:07
This one. Only when I change the name of a .md file and have backlinks to the document.

[cid:0aa5640c-b0fb-4180-ac34-d1c22333188e]

My settings ↴

[cid:af16bffb-e352-4307-8862-305bdef5a190]

BR
Antonio
________________________________
De: Michael Naumov ***@***.***>
Enviado: viernes, 13 de septiembre de 2024 16:03
Para: RainCat1998/obsidian-custom-attachment-location ***@***.***>
Cc: Kayfum ***@***.***>; Author ***@***.***>
Asunto: Re: [RainCat1998/obsidian-custom-attachment-location] When I rename a .md file, don't update backlinks - error with this plugin is displayed (Issue #96)


Which error are you getting?

**Comment by mnaoumov** [comment] 2024-09-13 14:09
Images were not attached

**Comment by mnaoumov** [comment] 2024-09-14 05:25
Still don't see the images

**Comment by Kayfum** [comment] 2024-09-14 21:15
They are in my email as attachment
________________________________
De: Michael Naumov ***@***.***>
Enviado: Saturday, September 14, 2024 7:25:41 AM
Para: RainCat1998/obsidian-custom-attachment-location ***@***.***>
Cc: Kayfum ***@***.***>; Author ***@***.***>
Asunto: Re: [RainCat1998/obsidian-custom-attachment-location] When I rename a .md file, don't update backlinks - error with this plugin is displayed (Issue #96)


Still don't see the images

**Comment by mnaoumov** [comment] 2024-09-17 03:23
Not in my email. Please resend them

**Comment by mnaoumov** [comment] 2024-09-18 00:53
Closing as no details provided

**Comment by ystlong** [comment] 2024-12-05 01:47
I encountered the same issue, and here is a video showing the error I’m experiencing.  

The custom-attachment-location is very useful for me, but there’s an issue when renaming files—backlinks do not sync properly.  

Thank you.  

https://github.com/user-attachments/assets/ac25ddad-a78f-4c05-aace-9f3086241c6f

**Comment by mnaoumov** [comment] 2024-12-05 01:51
@ystlong I cannot reproduce your issue. Please attach the sample vault with the problem. Please also tell me if you have the latest version of Obsidian and the plugin?

**Comment by ystlong** [comment] 2024-12-05 02:13
@mnaoumov 

Here is my vault: https://github.com/ystlong/test-obs 

My Obidian version:  v1.6.7 (Obsidian-1.6.7.AppImage)

**Comment by ystlong** [comment] 2024-12-05 02:19
I'm sorry , I just try the Obsidian-1.7.7.AppImage (latest version) with no problem.

Thanks.

**Comment by mnaoumov** [comment] 2024-12-05 02:20
@ystlong Please update to the latest Obsidian and to the latest plugin version. It seems I already fixed it in the latest version but it uses newer Obsidian API

**Closed** 2024-12-05 02:20 UTC
Labels: question
